pipeline {
    agent any
    tools {
      maven 'maven'
      jdk 'java17'
    }
    stages {
        stage('compile') {
		   steps {
                echo 'compiling..'
                dir("/var/lib/jenkins/workspace/trade-eureka-server-compilation/OrderBookEurekaServer") {
                    sh 'mvn compile'
                }

				 }
		}
	stage('codereview-pmd') {
		   steps {
			echo 'codereview..'
			sh 'mvn -f /var/lib/jenkins/workspace/trade-eureka-server-compilation/OrderBookEurekaServer/pom.xml pmd:pmd '
			}
		   post {
				   success {
				   	recordIssues enabledForFailure: true, tool: pmdParser(pattern: '**/target/pmd.xml')
				   }
			   }
		}
        stage('unit-test') {
		   steps {
					echo 'codereview..'
			   dir("/var/lib/jenkins/workspace/trade-eureka-server-compilation/OrderBookEurekaServer") {
					sh 'mvn test'
			   }
			}
		   post {
				   success {
					   junit 'target/surefire-reports/*.xml'
				   }
			   }
			}
        stage('code-coverage-stage') {
		   steps {
					echo 'unit test..'
			   dir("/var/lib/jenkins/workspace/trade-eureka-server-compilation/OrderBookEurekaServer") {
					sh 'mvn verify'
			   }
				}
		   post {
				   success {

						jacoco(
							execPattern: '**/target/**.exec',
							classPattern: '**/target/classes',
							sourcePattern: '**/src',
							inclusionPattern: 'com/tradeteam/**',
							changeBuildStatus: true
						)
				   }
			   }
        }
        stage('Package') {
		   steps {
					echo 'Packaging..'
			   dir("/var/lib/jenkins/workspace/trade-eureka-server-compilation/OrderBookEurekaServer") {
					sh 'mvn package'
			   }
			   }
        }

        stage ('Deploy') {
	      steps {
	        script {
	          deploy adapters: [tomcat9(credentialsId: 'mysecret-id', path: '', url: 'http://44.211.46.161:8085')], contextPath: '/tradeeurekaserver', onFailure: false, war: 'target/*.war'
	        }
	      }
    }


    }
}
